services:
  - type: web
    name: mongodb-tiny-social-media-api
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production